### PR TITLE
Motor refactor

### LINKED ISSUE #12: Refactor motors
Refactor Motors into two separate objects (that extend an abstract motor) and methods (`getLargeMotor(Port )` & `getSmallMotor(Port )`), dump motor objects into a motor package at the same time.

### PR DESCRIPTION
**Pull request by Robadob**
Fixes #12 

I'm going to leave this pull request for you to merge Ramsay

Addition/Changes include:
- Changed `PortManager` to be generic, so that Action-Argument/Return pairs could be used.
- Adjusted `close()` so that it calls `stop()` and waits for the motor to stop, previously asynchronous rotations were causing the motors to not disconnect cleanly, requiring robot restarts.
-  Added functionality for
  - `setSpeed()`
  - `getSpeed()`
  - `getMaxSpeed()`
  - `isStalled()`
  - `isMoving()`
  - `getTachoCount()`
  - `resetTachoCount()`
  - `rotate(degrees, async)`
  - `rotateTo(degrees, async)`
- All functionality should be documented

Notes:
- I've tested all the added functionality so there should be no huge bugs.
- The methods like `getSpeed()` have been implemented so that they return synchronously with other calls to the Motor, otherwise a call to `getSpeed()` directly after `setSpeed()` returns the old speed.
- Didn't add them into a sub-package in the end, due to protected not allowing sub-packages access.
- It may be useful to add an asynchronous `Motor.sleep(duration)` method, so students can do more complex multi motor timings.

### CODE REVIEW

**Comment by ramsay-t** [comment]
It looks good, my only concern is the close() method. I can’t remember exactly how it was supposed to work but there was some subtly in the way the Robot.close() called the Motor.close() and vice versa - they have to clear some attribute first otherwise they will enter an infinite mutual recursion.

We should really write some tests. I might even use if for test generation research :)

**Comment by Robadob** [comment]
> my only concern is the close() method. I can’t remember exactly how it was
> supposed to work but there was some subtly in the way the `Robot.close()`
> called the `Motor.close()`

Well I haven't changed `Robot.close()`, and I only changed `Motor.close()`
because I had to keep restarting the Robot after
using asynchronous rotations.

I tried adding something that would leave it waiting for the action to
complete, however it didn't seem to be able to tell the difference between
asynchronous rotate and `Motor.forward()`, so i just added a call to
`Motor.stop()` and then wait for it to actually stop.

**Comment by Robadob** [comment]
If you check the actual change, its more of an addition.

I'm going to start refactoring the existing sensors soon.

**Comment by Robadob** [comment]
My only concern is whether I need to do anything fancy to be thread-safe
when reading return values on the motor's getters (because there might be a
tiny chance of it reading at the same time as it's being written).

**Comment by ramsay-t** [comment]
Call it “eventually consistent” and ignore it, thats the 21st century solution :)

**Pull request merged**
