### PR TITLE
Added git ignore, blocks binaries, buildscripts and documentation.

### PR DESCRIPTION
**Pull request by Robadob**
Users who wish to generate binaries or documentation should follow the Readme.

Also standardised indentation (didn't realise when I pull request from master, it follows any new commits.)

### CODE REVIEW

**Comment by Robadob** [comment]
Really? I thought emacs was better than that (i used 4 spaces per tab because that seems pretty standard).

If you were handing in such inconsistent indentation for  COM1003 assignment, you would lose marks for it, it makes it challenging to read.

**Comment by ramsay-t** [comment]
Its perfectly _consistently_ indented, just maybe not the way you like :)

If it looks inconsistent I would check your display settings. Unless it uses a mix of tabs and spaces, then I blame emacs, but looking at the patch details you have substitued one depth of spacing for another consistently.

Plus I didn’t even think this was valid:

private LinkedList <String> actions;

**Comment by Robadob** [comment]
Consistent means you indent everything within `{}` by the same amount. It may have been a result of mixed spaces and tabs (I have my editor setup to tab==2 spaces, so a mix of 4 spaces and tab chars could cause it to come out dodgy), because it was looking like [this](https://dl.dropboxusercontent.com/u/2461478/12185949_10153192572118176_1078557611_o.jpg) for me.

`private LinkedList <String> actions;` is valid, you just receive a runtime error if you try to access it before it's been initialised. I haven't made any non-cosmetic changes yet.

**Comment by ramsay-t** [comment]
> Consistent means you indent everything within {} by the same amount. It may have been a result of mixed spaces and tabs (I have my editor setup to tab==2 spaces, so a mix of 4 spaces and tab chars could cause it to come out dodgy), because it was looking like this https://dl.dropboxusercontent.com/u/2461478/12185949_10153192572118176_1078557611_o.jpg for me.

I blame your settings :)

https://www.dropbox.com/s/wmul41rx949tc6b/Screen%20Shot%202015-10-27%20at%2019.30.01.png?dl=0

> private LinkedList <String> actions; is valid, you just receive a runtime error if you try to access it before it's been initialised. I haven't made any non-cosmetic changes yet.
> 
> I meant the space between the LinkedList and the angle brackets — in a “real” language like Z in LaTeX the type parameters would be subscripts, so it makes more sense to me that they be physically attached to the class name… I guess it compiles either way but I’m not sure I agree that this way is more beautiful!

**Comment by Robadob** [comment]
Yeah that makes sense, but I've never seen them written with spaces, [throughout the JavaDocs](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html), you can see them used many times without. Presumably it's a result of the fact you can't use `<` or `>` within identifiers.

**Comment by ramsay-t** [comment]
Perhaps you misunderstand - I’m accusing you of ADDING the spaces! :)

**Comment by Robadob** [comment]
Ah, yeah it must have been the beautifier I used to automate cleaning it up. I thought I had removed them all, I guess i missed a few I'll fix them later.

**Pull request merged**
